CFLAGS = -std=gnu11 -Wall -Werror -Wextra -fopenmp -Ofast

.PHONY: all
all: array bufferarray localsum

.PHONY: clean
clean:
	$(RM) array bufferarray localsum

array: array.c array

bufferarray: bufferarray.c bufferarray

localsum: localsum.c localsum