CFLAGS = -std=gnu11 -Wall -Werror -Wextra -fopenmp -O1

.PHONY: all
all: compiler_specific_program

.PHONY: clean
clean:
	$(RM) compiler_specific_program

compiler_specific_program: compiler_specific_program.c compiler_specific_program