CFLAGS = --std=gnu11 -Wall -Wextra 

.PHONY: all
all: hadamard_01 hadamard_02 hadamard_demo

.PHONY: clean
clean:
	$(RM) hadamard_01 hadamard_02 hadamard_demo

hadamard_01: hadamard_01.c

hadamard_02: hadamard_02.c

hadamard_demo: hadamard_demo.c